Storehouse/Storehouse.ASPNet/Controllers/ProductController.cs
using Storehouse.Core;
using Storehouse.Core.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Storehouse.ASPNet.Controllers
{
    public class ProductController : Controller
    {
        WarehouseOneEntitiesL db = new WarehouseOneEntitiesL();
        private UnitOfWork unitOfWork;
        public ProductController()
        {
            unitOfWork = new UnitOfWork();
        }
        // GET: Product
        [Authorize]
        public ActionResult Index()
        {
            var model = unitOfWork.Products.GetAll();
            return View(model);
        }
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.ProviderId = new SelectList(db.Providers, "Id", "ProviderName");
            ViewBag.TypeId = new SelectList(db.TypeProducts, "Id", "TypeName");
            ViewBag.StorageId = new SelectList(db.Storages, "Id", "Name");
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult Create(Product p)
        {
            if(ModelState.IsValid)
            {
                unitOfWork.Products.Create(p);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(p);
        }
        [Authorize]
        public ActionResult Edit(int id)
        {
            Product product = unitOfWork.Products.Get(id);
            if(product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        [Authorize]
        [HttpPost]
        public ActionResult Edit(Product item)
        {
            unitOfWork.Products.Update(item);
            unitOfWork.Save();
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult Delete(int id)
        {
            unitOfWork.Products.Delete(id);
            unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

Storehouse/Storehouse.ASPNet/Controllers/ProviderController.cs
using Storehouse.Core;
using Storehouse.Core.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Storehouse.ASPNet.Controllers
{
    public class ProviderController : Controller
    {
        private UnitOfWork unitOfWork;
        public ProviderController()
        {
            unitOfWork = new UnitOfWork();
        }
        // GET: Provider
        [Authorize]
        public ActionResult Index()
        {
            var model = unitOfWork.Providers.GetAll();
               
            return View(model);
        }
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult Create(Provider p)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Providers.Create(p);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(p);
        }
        [Authorize]
        public ActionResult Edit(int id)
        {
            Provider provider = unitOfWork.Providers.Get(id);
            if(provider == null)
            {
                return HttpNotFound();
            }
            return View(provider);
        }
        [Authorize]
        [HttpPost]
        public ActionResult Edit(Provider item)
        {
            unitOfWork.Providers.Update(item);
            unitOfWork.Save();
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult Delete(int id)
        {
            unitOfWork.Providers.Delete(id);
            unitOfWork.Save();
            return RedirectToAction("Index");
        }
        [Authorize]
        protected override void Dispose(bool disposing)
        {
            unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

Storehouse/Storehouse.ASPNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div style="background: #723D46;" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Warehouse", "Index", "Product", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Product", "Index", "Product")</li>
                    <li>@Html.ActionLink("Providers", "Index", "Provider")</li>
                    <li>@Html.ActionLink("Types", "Index", "Types")</li>
                    <li>@Html.ActionLink("Storage", "Index", "Warehouse")</li>
                </ul>
                <ul style="float: right;" class="nav navbar-nav">
                    <li>@Html.ActionLink("Log out", "Logout", "Account")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Warehouse - develop and design by Artem Vatsyk</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>